version: '3.7'

services:
  app:
    build:
      context: .
    network_mode: "bridge"
    container_name: $CI_PROJECT_NAME
    ports:
      - 3014:3014
    volumes:
      - .:/usr/app
    restart: always